version: '1.0'

services:
  api:
    container_name: "wicon-api"
    volumes:
      - ./app:/app
    build: .
    tty: True
    restart: always
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
